targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          create_to_json: true
          checked: true
      freezed:
        options:
          use_wrappers: true
          union_key: union
          generate_to_json: true
          generate_from_json: true
          generate_part_of: true
          generate_copy_with: true
          generate_to_string: true
          generate_json_methods: true
          generate_to_json_methods: true
          generate_from_json_methods: true
          generate_to_json_key_methods: true
          generate_copy_with_methods: true
          create_factory: true
          create_to_json: true
          copy_with: true
          equal: true
          map: true
          when: 
            when: true
            maybe_when: false
            when_or_null: false
      build_runner:
        generate_for:
          - lib/**
        options:
          delete_conflicting_outputs: true

