name: home_service_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^2.0.10
  google_fonts: ^5.1.0
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  go_router: ^10.0.0
  gap: ^3.0.1
  line_icons: ^2.0.3
  liquid_swipe: ^3.1.0
  logger: ^2.0.2+1
  flutter_native_splash: ^2.3.2
  chat_bubbles: ^1.5.0
  shimmer: ^3.0.0
  flutter_facebook_auth: ^6.0.1
  flutter_svg: ^2.0.7
  change_app_package_name: ^1.1.0
  equatable: ^2.0.0
  google_sign_in: ^6.1.4
  flutter_staggered_grid_view: ^0.7.0
  pinput: ^3.0.1
  smooth_page_indicator: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_google_maps_webservices: ^1.1.1
  location: ^5.0.3
  flow_builder: ^0.0.10

  ## --- FIREBASE FIRESTORE PACKAGES
  cloud_firestore: ^4.3.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.5.6
  agora_rtc_engine: ^6.2.6
  readmore: ^2.2.0
  permission_handler: ^11.1.0
  google_maps_flutter: ^2.5.0
  flutter_rating_bar: ^4.0.1
  formz: ^0.6.1
  hydrated_bloc: ^7.1.0
  meta: ^1.10.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1

flutter_native_splash:
  color: "#007AFF"
  image: assets/images/app-logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

