name: home_service_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  go_router: ^10.0.0
  line_icons: ^2.0.3
  liquid_swipe: ^3.1.0
  flutter_native_splash: ^2.3.2
  chat_bubbles: ^1.5.0
  shimmer: ^3.0.0
  flutter_facebook_auth: ^6.0.1
  flutter_svg: ^2.0.7
  equatable: ^2.0.0
  google_sign_in: ^6.1.4
  pinput: ^3.0.1
  smooth_page_indicator: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  ## --- FIREBASE FIRESTORE PACKAGES
  cloud_firestore: ^4.3.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0


flutter_native_splash:
    color: "#007AFF"
    image: assets/images/app-logo.png
    android: true
    ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
