name: service_masters
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  
  
  agora_rtc_engine: ^6.2.6
  animations: ^2.0.8
  auto_route: ^7.8.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.0.0
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.3.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_google_maps_webservices: ^1.1.1
  flutter_hooks: ^0.20.4
  flutter_native_splash: ^2.3.10
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.3
  image_cropper: ^5.0.1
  image_picker: ^1.0.5
  intl: ^0.19.0
  json_annotation: ^4.8.1
  liquid_swipe: ^3.1.0
  logger: ^2.0.2+1
  meta: ^1.9.1
  multiple_result: ^5.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  pinput: ^4.0.0
  readmore: ^2.2.0
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_sliders: ^25.1.35
  uuid: ^4.4.0


flutter_native_splash:
  color: "#007AFF"
  image: assets/images/app-logo.png
  android: true
  ios: true

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

