// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        "DefaultFirebaseOptions have not been configured for web - "
        "you can reconfigure this by running the FlutterFire CLI again.",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB5Md6KvDPim91477vSqaHjVQ_MyFwjrkQ",
    appId: "1:722865947054:android:1ece31f1e012d640cd083f",
    messagingSenderId: "722865947054",
    projectId: "service-masters-d5bc8",
    storageBucket: "service-masters-d5bc8.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyClvFmr1eHdvX8L4_8HMmp720pvlA0ThxM",
    appId: "1:722865947054:ios:495c9ad96e66b00dcd083f",
    messagingSenderId: "722865947054",
    projectId: "service-masters-d5bc8",
    storageBucket: "service-masters-d5bc8.appspot.com",
    androidClientId: "722865947054-3co407p4dqabkvarnpqg2kdspltroslq.apps.googleusercontent.com",
    iosClientId: "722865947054-lcqql1o0dvr7evmjdjshu8c2qf7vqmlv.apps.googleusercontent.com",
    iosBundleId: "com.service.masters.serviceMasters",
  );
}
